#!/usr/bin/env python
# vim:fileencoding=utf-8:noet
from __future__ import (unicode_literals, division, absolute_import, print_function)

import time
import re
import subprocess

from threading import Lock, Timer

from powerline.lemonbar import LemonbarPowerline
from powerline.commands.lemonbar import get_argparser
from powerline.bindings.wm import get_connected_xrandr_outputs


if __name__ == '__main__':

	def execute(process, shell):
		for stdout_line in iter(process.stdout.readline, b''):
			print("execute: " + str(stdout_line))
			if shell:
				shell.stdin.write(stdout_line)
				shell.stdin.flush()
			yield stdout_line
		process.stdout.close()

	parser = get_argparser()
	args = parser.parse_args()

	powerline = LemonbarPowerline()
	powerline.update_renderer()
	bars = []
	execs = []
	shell = None
	if args.clicks:
		shell = subprocess.Popen(['/bin/sh'], stdin=subprocess.PIPE)


	for screen in get_connected_xrandr_outputs(powerline.pl):
		command = [args.bar_command, '-g', '{0}x{1}+{2}+{3}'.format(screen['width'], args.height, screen['x'], screen['y'])] + args.args[1:]
		process = subprocess.Popen(command, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
		bars.append((screen['name'], process, int(screen['width']) / 5))
		execs.append(execute(process, shell))

	lock = Lock()
	modes = ['default']

	def render(reschedule=False):
		t = Timer(args.interval, render, kwargs={'reschedule': True})

		global lock
		with lock:
			try:
				for output, process, width in bars:
					process.stdin.write(powerline.render(mode=modes[0], width=width, matcher_info=output).encode('utf-8') + b'\n')
					process.stdin.flush()
				if reschedule:
					t.start()
			except BrokenPipeError:
				# The lemonbar died, so should we
				pass

	def update(evt):
		modes[0] = evt.change
		render()

	render(reschedule=True)

	for e in execs:
		for ls in e:
			print(ls)

	if args.i3:
		import i3ipc
		conn = i3ipc.Connection()
		while True:
			conn.on('workspace::focus', lambda conn, evt: render())
			conn.on('mode', lambda conn, evt: update(evt))
			render()
			conn.main()
			time.sleep(1) # If this gets executed, i3 got restarted / crashed / whatever
			conn = i3ipc.Connection()
			powerline = LemonbarPowerline()
			powerline.update_renderer()

	while True:
		sleep(1e8)
